project_id = "uuiaijoxmhccbdqnfblo"

[functions.create-payment-link]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.initiate-payment]
verify_jwt = false

[functions.send-telegram-signal]
verify_jwt = false
